In [2]:
import pandas as pd
from glob import glob
import os

In [3]:
data_dir = '../data/raw'
# Buscar todos los CSV de la carpeta
accident_files = sorted(glob(os.path.join(data_dir, "*.csv")))
accident_files

['../data/raw/2017_accidents_gu_bcn.csv',
 '../data/raw/2018_accidents_gu_bcn.csv',
 '../data/raw/2019_accidents_gu_bcn.csv',
 '../data/raw/2020_accidents_gu_bcn.csv',
 '../data/raw/2021_accidents_gu_bcn.csv',
 '../data/raw/2022_accidents_gu_bcn.csv',
 '../data/raw/2023_accidents_gu_bcn.csv',
 '../data/raw/2024_accidents_gu_bcn.csv']

In [4]:
# Leer y unir todos los archivos
df_accidents = pd.concat([pd.read_csv(file) for file in accident_files], ignore_index=True)
df_accidents

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Coordenada_UTM_Y,Longitud,Latitud,Num_postal,Num_postal_caption,NK_Any,Coordenada_UTM_X_ED50,Coordenada_UTM_Y_ED50,Longitud_WGS84,Latitud_WGS84
0,2017S008429,-1,Desconegut,-1,Desconegut,-1,Número 27 ...,Desconegut,Divendres,Dv,...,4577079.15,2.125624,41.340045,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017S007316,-1,Desconegut,-1,Desconegut,-1,Número 3 Zona Franca / Número 50 Zona Franca ...,Desconegut,Divendres,Dv,...,4577014.83,2.120452,41.339426,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017S010210,-1,Desconegut,-1,Desconegut,-1,Litoral (Besòs) ...,K128,Divendres,Dv,...,4579358.49,2.167356,41.360886,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017S006364,-1,Desconegut,-1,Desconegut,-1,Número 3 Zona Franca ...,77-111,Divendres,Dv,...,4576816.19,2.124529,41.337668,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017S004615,10,Sant Martí,64,el Camp de l'Arpa del Clot,226400,Las Navas de Tolosa ...,0323 0325,Dijous,Dj,...,"4585503,52",2.185272,41.416365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67483,2024S007547,2,Eixample,7,la Dreta de l'Eixample,169409,Corts Catalanes,NaN,Dimarts,NaN,...,NaN,NaN,NaN,603,NaN,2024.0,4582460.824,430450.705,2.167002,41.388825
67484,2024S007548,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",143100,General Álvarez de Castro,NaN,Dissabte,NaN,...,NaN,NaN,NaN,2-4,NaN,2024.0,4582233.737,431382.242,2.178169,41.386859
67485,2024S007549,3,Sants-Montjuïc,11,el Poble Sec,198804,Paral·lel,NaN,Dijous,NaN,...,NaN,NaN,NaN,NaN,NaN,2024.0,4580940.29,428989.313,2.149703,41.375002
67486,2024S007550,3,Sants-Montjuïc,11,el Poble Sec,234001,Olímpic,NaN,Dilluns,NaN,...,NaN,NaN,NaN,1-3,NaN,2024.0,4579426.054,429206.725,2.152479,41.361383
67487,2024S007551,1,Ciutat Vella,1,el Raval,701367,Raval,NaN,Divendres,NaN,...,NaN,NaN,NaN,25X,NaN,2024.0,4581341.695,430668.432,2.169734,41.378764

In [24]:
df_accidents[df_accidents["Any"] == 2023]

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Numero_vehicles_implicats,Coordenada_UTM_X,Coordenada_UTM_Y,Longitud,Latitud,Num_postal_caption,Coordenada_UTM_X_ED50,Coordenada_UTM_Y_ED50,Longitud_WGS84,Latitud_WGS84
52228,2023S000001,3,Sants-Montjuïc,18,Sants,30602,Badal / Càceres ...,0186 0186,Diumenge,NaN,...,1,NaN,NaN,NaN,NaN,NaN,4580907.46,427409.24,2.130813,41.374565
52229,2023S000002,7,Horta-Guinardó,33,el Baix Guinardó,109203,Encarnació ...,0149 0149,Diumenge,NaN,...,1,NaN,NaN,NaN,NaN,NaN,4584798.12,430348.68,2.165513,41.409867
52230,2023S000003,1,Ciutat Vella,1,el Raval,67307,Carme ...,0075 0079,Diumenge,NaN,...,1,NaN,NaN,NaN,NaN,NaN,4581533.3,430479.42,2.167452,41.380473
52231,2023S000005,6,Gràcia,31,la Vila de Gràcia,282401,Riera de Sant Miquel / Sèneca ...,0017 0017,Diumenge,NaN,...,2,NaN,NaN,NaN,NaN,NaN,4583426.13,429637.2,2.157161,41.397448
52232,2023S000006,6,Gràcia,31,la Vila de Gràcia,206403,Gran de Gràcia / Gràcia ...,0072 0072,Diumenge,NaN,...,2,NaN,NaN,NaN,NaN,NaN,4583693.13,429497.51,2.155459,41.399841
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59947,2023S007738,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,701265,Litoral (Besòs) ...,000600000,Dimarts,NaN,...,2,NaN,NaN,NaN,NaN,NaN,4584321.79,434743.24,2.218139,41.405946
59948,2023S007739,6,Gràcia,32,el Camp d'en Grassot i Gràcia Nova,297001,Sant Antoni Maria Claret / Llavallol ...,0045 0045,Divendres,NaN,...,2,NaN,NaN,NaN,NaN,NaN,4584328.63,430464.89,2.166957,41.405649
59949,2023S007740,4,Les Corts,20,la Maternitat i Sant Ramon,144601,Diagonal ...,0687 0687,Dissabte,NaN,...,3,NaN,NaN,NaN,NaN,NaN,4581831.03,425387.6,2.106527,41.382698
59950,2023S007741,4,Les Corts,20,la Maternitat i Sant Ramon,244209,Joan XXIII ...,0017 0017,Divendres,NaN,...,1,NaN,NaN,NaN,NaN,NaN,4581953.15,426661.83,2.121750,41.383916
59951,2023S007742,4,Les Corts,20,la Maternitat i Sant Ramon,701434,Carles III / Mejía Lequerica ...,000220000,Divendres,NaN,...,2,NaN,NaN,NaN,NaN,NaN,4582038.85,427133.55,2.127381,41.384730

In [5]:
df_accidents.shape

(67488, 34)

In [6]:
df_accidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67488 entries, 0 to 67487
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Numero_expedient           67488 non-null  object
 1   Codi_districte             67488 non-null  int64
 2   Nom_districte              67488 non-null  object
 3   Codi_barri                 67488 non-null  object
 4   Nom_barri                  67488 non-null  object
 5   Codi_carrer                67488 non-null  int64
 6   Nom_carrer                 67486 non-null  object
 7   Num_postal                 10339 non-null  object
 8   Descripcio_dia_setmana     67488 non-null  object
 9   Dia_setmana                36570 non-null  object
 10  Descripcio_tipus_dia       36570 non-null  object
 11  Any                        20275 non-null  float64
 12  Mes_any                    67488 non-null  int64
 13  Nom_mes                    67488 non-null  object
 14  Dia_mes                    67488 non-null  int64
 15  Hora_dia                   67488 non-null  int64
 16  Descripcio_torn            67488 non-null  object
 17  Descripcio_causa_vianant   60423 non-null  object
 18  Numero_morts               59963 non-null  float64
 19  Numero_lesionats_lleus     66480 non-null  float64
 20  Numero_lesionats_greus     60193 non-null  float64
 21  Numero_victimes            66672 non-null  float64
 22  Numero_vehicles_implicats  67488 non-null  int64
 23  Coordenada_UTM_X           36570 non-null  object
 24  Coordenada_UTM_Y           36570 non-null  object
 25  Longitud                   44569 non-null  float64
 26  Latitud                    44569 non-null  float64
 27  Num_postal                 17283 non-null  object
 28  Num_postal_caption         31953 non-null  object
 29  NK_Any                     47213 non-null  float64
 30  Coordenada_UTM_X_ED50      30918 non-null  object
 31  Coordenada_UTM_Y_ED50      30918 non-null  object
 32  Longitud_WGS84             22895 non-null  float64
 33  Latitud_WGS84              22895 non-null  float64
dtypes: float64(10), int64(6), object(18)
memory usage: 17.5+ MB

In [7]:
df_accidents.describe().T

,count,mean,std,min,25%,50%,75%,max
Codi_districte,67488.0,4.868243,3.013772,-1.000000,2.000000,4.000000,7.000000,10.000000
Codi_carrer,67488.0,247783.118169,200040.713513,-1.000000,115400.000000,191204.000000,320908.000000,701918.000000
Any,20275.0,2017.490062,0.499914,2017.000000,2017.000000,2017.000000,2018.000000,2018.000000
Mes_any,67488.0,6.534554,3.462213,1.000000,4.000000,7.000000,10.000000,12.000000
Dia_mes,67488.0,15.717150,8.779916,1.000000,8.000000,16.000000,23.000000,31.000000
Hora_dia,67488.0,13.828266,5.320445,0.000000,10.000000,14.000000,18.000000,23.000000
Numero_morts,59963.0,0.002285,0.047745,0.000000,0.000000,0.000000,0.000000,1.000000
Numero_lesionats_lleus,66480.0,1.153309,0.754789,0.000000,1.000000,1.000000,1.000000,25.000000
Numero_lesionats_greus,60193.0,0.027345,0.175739,0.000000,0.000000,0.000000,0.000000,6.000000
Numero_victimes,66672.0,1.176731,0.749221,0.000000,1.000000,1.000000,1.000000,26.000000
Numero_vehicles_implicats,67488.0,1.886898,0.717799,0.000000,2.000000,2.000000,2.000000,18.000000
Longitud,44569.0,3.128052,45.621050,-1.488576,2.145109,2.163811,2.180220,2188.000000
Latitud,44569.0,59.934192,875.557565,0.000009,41.385887,41.397111,41.411475,41414.000000
NK_Any,47213.0,2021.417957,1.751577,2019.000000,2020.000000,2021.000000,2023.000000,2024.000000
Longitud_WGS84,22895.0,2.162846,0.024417,2.058047,2.144797,2.163447,2.180530,2.223673
Latitud_WGS84,22895.0,41.400521,0.022460,41.322721,41.385918,41.397848,41.413622,41.467466

In [8]:
df_accidents['Dia_setmana'].value_counts()

Dia_setmana
Dv    5122
Dj    4923
Dc    4915
Dm    4879
Dl    4530
Ds    3338
Dg    2595
4     1104
5     1032
3     1023
1      972
2      933
6      686
7      518
Name: count, dtype: int64

In [9]:
# Ver si hay valores duplicados del numero de expediente
duplicados = df_accidents[df_accidents["Numero_expedient"].duplicated()]
duplicados

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Coordenada_UTM_Y,Longitud,Latitud,Num_postal,Num_postal_caption,NK_Any,Coordenada_UTM_X_ED50,Coordenada_UTM_Y_ED50,Longitud_WGS84,Latitud_WGS84
5800,2017S003286,3,Sants-Montjuïc,13,la Marina de Port,109906,Energia ...,0001X0001X,Dilluns,Dl,...,"4579006,9",2.136744,41.357598,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6492,2017S008856,10,Sant Martí,71,Provençals del Poblenou,30409,Diagonal / Bac de Roda ...,0100 0108,Dijous,Dj,...,"4584557,54",2.203962,41.407568,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6979,2017S003750,2,Eixample,7,la Dreta de l'Eixample,357001,Bergara ...,0014 0014,Dijous,Dj,...,"4582179,48",2.168836,41.386306,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9211,2017S004447,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,701278,Taulat ...,0136 0136,Divendres,Dv,...,"4583913,96",2.209813,41.402218,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10655,2018S003156,3,Sants-Montjuïc,16,la Bordeta,169409,Corts Catalanes ...,NaN,Dimarts,Dm,...,4579751.39,2.133801,41.364177,111-119,NaN,NaN,NaN,NaN,NaN,NaN
10784,2018S002285,3,Sants-Montjuïc,16,la Bordeta,89707,Constitució ...,NaN,Dijous,Dj,...,4580251.36,2.132499,41.368671,155,NaN,NaN,NaN,NaN,NaN,NaN
11548,2018S002968,3,Sants-Montjuïc,17,Sants - Badal,187207,Madrid ...,NaN,Dimecres,Dc,...,4581285.13,2.126816,41.377939,68,NaN,NaN,NaN,NaN,NaN,NaN
11591,2018S009504,2,Eixample,10,Sant Antoni,127704,Floridablanca / Viladomat ...,NaN,Dijous,Dj,...,4581335.47,2.158684,41.378630,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12870,2018S005992,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",177101,Laietana ...,NaN,Dijous,Dj,...,4582187.93,2.175646,41.386431,46,NaN,NaN,NaN,NaN,NaN,NaN
13124,2018S001774,4,Les Corts,20,la Maternitat i Sant Ramon,144601,Diagonal ...,NaN,Diumenge,Dg,...,4582337.48,2.125516,41.387409,629,NaN,NaN,NaN,NaN,NaN,NaN
14651,2018S000261,5,Sarrià-Sant Gervasi,23,Sarrià,305201,Sant Joan Bosco / Maria Auxiliadora ...,NaN,Dijous,Dj,...,4583076.17,2.127990,41.394081,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16010,2018S002344,5,Sarrià-Sant Gervasi,26,Sant Gervasi - Galvany,143904,General Mitre ...,NaN,Dissabte,Ds,...,4583745.01,2.135246,41.400160,92-94,NaN,NaN,NaN,NaN,NaN,NaN
17263,2018S001500,6,Gràcia,31,la Vila de Gràcia,290206,Torrent de les Flors / Rovira i Trias ...,NaN,Dissabte,Ds,...,4584552.91,2.158799,41.407612,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17379,2018S000183,6,Gràcia,32,el Camp d'en Grassot i Gràcia Nova,356304,Taxdirt / Ventalló ...,NaN,Dilluns,Dl,...,4584642.04,2.164942,41.408460,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30935,2020S000638,5,Sarrià-Sant Gervasi,51-5-26,Sant Gervasi - Galvany,344101,Gràcia,NaN,Dilluns,1,...,4583295.6,2.149556,41.396216,NaN,0051 0051,2020.0,NaN,NaN,NaN,NaN
31076,2020S000778,9,Sant Andreu,91-9-63,Navas,209900,Meridiana,NaN,Dijous,4,...,4585841.6,2.186612,41.419417,NaN,0235 0235,2020.0,NaN,NaN,NaN,NaN
31253,2020S000956,2,Eixample,23-2-8,l'Antiga Esquerra de l'Eixample,350308,València,NaN,Dissabte,6,...,4582643.19,2.160104,41.390417,NaN,0211 0211,2020.0,NaN,NaN,NaN,NaN
33958,2020S003665,2,Eixample,25-2-6,la Sagrada Família,178308,Lepant,NaN,Dijous,4,...,4584077.09,2.178158,41.403463,NaN,0258 0258,2020.0,NaN,NaN,NaN,NaN
34772,2020S004479,5,Sarrià-Sant Gervasi,53-5-25,Sant Gervasi - la Bonanova,701268,Dalt (Llobregat),NaN,Dimarts,2,...,4585391.51,2.136151,41.414995,NaN,940000,2020.0,NaN,NaN,NaN,NaN
34883,2020S004590,8,Nou Barris,82-8-49,Canyelles,120807,Favència,NaN,Dijous,4,...,4588348.41,2.166402,41.441853,NaN,0041 0045,2020.0,NaN,NaN,NaN,NaN
35587,2020S005294,4,Les Corts,42-4-20,la Maternitat i Sant Ramon,187207,Madrid,NaN,Dimecres,3,...,4581210.7,2.125031,41.377253,NaN,0039 0041,2020.0,NaN,NaN,NaN,NaN
39132,2021S000395,6,Gràcia,28,Vallcarca i els Penitents,123408,Lesseps,NaN,Dimarts,NaN,...,NaN,NaN,NaN,NaN,0021X0021X,2021.0,429024.35,4584481.54,2.149706,41.406900
39836,2021S000847,2,Eixample,6,la Sagrada Família,90502,Còrsega,NaN,Dijous,NaN,...,NaN,NaN,NaN,NaN,0532 0532,2021.0,430891.22,4584360.4,2.172053,41.405971
42346,2021S001332,10,Sant Martí,64,el Camp de l'Arpa del Clot,161407,Indústria,NaN,Dimarts,NaN,...,NaN,NaN,NaN,NaN,0279 0281,2021.0,431670.92,4585357.49,2.181268,41.415019
42627,2021S002982,2,Eixample,8,l'Antiga Esquerra de l'Eixample,169409,Corts Catalanes,NaN,Dissabte,NaN,...,NaN,NaN,NaN,NaN,0583 0583,2021.0,430080.36,4582095.48,2.162615,41.385502
43329,2021S001951,10,Sant Martí,65,el Clot,161101,Independència,NaN,Dijous,NaN,...,NaN,NaN,NaN,NaN,0243 0243,2021.0,432003.59,4584366.47,2.185360,41.406121
43982,2021S005130,6,Gràcia,28,Vallcarca i els Penitents,158107,Vallcarca,NaN,Dijous,NaN,...,NaN,NaN,NaN,NaN,0133 0147,2021.0,428461.6,4585247.52,2.142883,41.413749
45517,2022S000750,2,Eixample,7,la Dreta de l'Eixample,169409,Corts Catalanes ...,NaN,Dimarts,NaN,...,NaN,2.165224,41.386804,NaN,0602 0602,2022.0,430299.85,4582237.63,NaN,NaN
48105,2022S000364,7,Horta-Guinardó,33,el Baix Guinardó,76807,Sardenya / Providència ...,NaN,Dissabte,NaN,...,NaN,2.163939,41.410488,NaN,0494 0494,2022.0,430217.78,4584868.03,NaN,NaN
48476,2022S007820,2,Eixample,8,l'Antiga Esquerra de l'Eixample,349706,Comte d'Urgell / Sarrià ...,NaN,Dimecres,NaN,...,NaN,2.148272,41.389882,NaN,0217 0223,2022.0,428885.89,4582593.13,NaN,NaN
49388,2022S001333,1,Ciutat Vella,1,el Raval,76501,Cera / Reina Amàlia ...,NaN,Dissabte,NaN,...,NaN,2.165245,41.378098,NaN,0040 0040,2022.0,430292.31,4581271.11,NaN,NaN
49507,2022S002608,2,Eixample,9,la Nova Esquerra de l'Eixample,350308,València ...,NaN,Dimarts,NaN,...,NaN,2.148623,41.381494,NaN,0064 0066,2022.0,428906.06,4581661.62,NaN,NaN
49527,2022S007071,2,Eixample,9,la Nova Esquerra de l'Eixample,54509,Calàbria / Diputació ...,NaN,Divendres,NaN,...,NaN,2.153920,41.380520,NaN,0115 0117,2022.0,429347.93,4581549.1,NaN,NaN
50367,2022S003249,10,Sant Martí,71,Provençals del Poblenou,169409,Corts Catalanes ...,NaN,Dissabte,NaN,...,NaN,2.204231,41.415753,NaN,1092 1094,2022.0,433590.68,4585420.82,NaN,NaN
50627,2022S000411,2,Eixample,6,la Sagrada Família,68900,Cartagena ...,NaN,Dilluns,NaN,...,NaN,2.178533,41.407851,NaN,0241 0241,2022.0,431434.74,4584563.62,NaN,NaN
50717,2022S007743,2,Eixample,5,el Fort Pienc,197302,Marina ...,NaN,Divendres,NaN,...,NaN,2.179451,41.400151,NaN,0191 0191,2022.0,431503.37,4583708.04,NaN,NaN
51395,2022S000209,1,Ciutat Vella,2,el Barri Gòtic,82901,Colom ...,NaN,Divendres,NaN,...,NaN,2.181484,41.381019,NaN,0001 0001,2022.0,431653.31,4581582.41,NaN,NaN
53302,2023S001079,6,Gràcia,31,la Vila de Gràcia,267000,Riera de Cassoles / Bretón de los Herreros ...,NaN,Dimecres,NaN,...,NaN,NaN,NaN,0008 0008,NaN,2023.0,4583923.03,429116.73,2.150877,41.401878
56937,2023S004724,10,Sant Martí,67,la Vila Olímpica del Poblenou,110009,Ramon Turró ...,NaN,Divendres,NaN,...,NaN,NaN,NaN,0037 0037,NaN,2023.0,4582848.16,432648.07,2.193239,41.392500
59066,2023S006857,2,Eixample,10,Sant Antoni,323203,Sepúlveda ...,NaN,Dissabte,NaN,...,NaN,NaN,NaN,0096 0096,NaN,2023.0,4581394.65,429629.64,2.157306,41.379150

In [10]:
# Encontrar los expedientes duplicados (que aparecen más de una vez)
duplicados_ids = df_accidents["Numero_expedient"][df_accidents["Numero_expedient"].duplicated(keep=False)]
duplicados_ids

84       2017S008856
3079     2017S003750
5222     2017S004447
5799     2017S003286
5800     2017S003286
              ...
53302    2023S001079
56936    2023S004724
56937    2023S004724
59065    2023S006857
59066    2023S006857
Name: Numero_expedient, Length: 80, dtype: object

In [11]:
# Filtrar todos los registros con los expedientes duplicados
expedientes_duplicados= df_accidents[df_accidents["Numero_expedient"].isin(duplicados_ids)]
expedientes_duplicados.sort_values("Numero_expedient")

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Coordenada_UTM_Y,Longitud,Latitud,Num_postal,Num_postal_caption,NK_Any,Coordenada_UTM_X_ED50,Coordenada_UTM_Y_ED50,Longitud_WGS84,Latitud_WGS84
5799,2017S003286,3,Sants-Montjuïc,13,la Marina de Port,109906,Energia ...,0001X0001X,Dilluns,Dl,...,"4579006,9",2.136744,41.357598,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5800,2017S003286,3,Sants-Montjuïc,13,la Marina de Port,109906,Energia ...,0001X0001X,Dilluns,Dl,...,"4579006,9",2.136744,41.357598,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3079,2017S003750,2,Eixample,7,la Dreta de l'Eixample,357001,Bergara ...,0014 0014,Dijous,Dj,...,"4582179,48",2.168836,41.386306,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6979,2017S003750,2,Eixample,7,la Dreta de l'Eixample,357001,Bergara ...,0014 0014,Dijous,Dj,...,"4582179,48",2.168836,41.386306,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5222,2017S004447,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,701278,Taulat ...,0136 0136,Divendres,Dv,...,"4583913,96",2.209813,41.402218,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53302,2023S001079,6,Gràcia,31,la Vila de Gràcia,267000,Riera de Cassoles / Bretón de los Herreros ...,NaN,Dimecres,NaN,...,NaN,NaN,NaN,0008 0008,NaN,2023.0,4583923.03,429116.73,2.150877,41.401878
56936,2023S004724,10,Sant Martí,67,la Vila Olímpica del Poblenou,110009,Ramon Turró ...,NaN,Divendres,NaN,...,NaN,NaN,NaN,0037 0037,NaN,2023.0,4582848.16,432648.07,2.193239,41.392500
56937,2023S004724,10,Sant Martí,67,la Vila Olímpica del Poblenou,110009,Ramon Turró ...,NaN,Divendres,NaN,...,NaN,NaN,NaN,0037 0037,NaN,2023.0,4582848.16,432648.07,2.193239,41.392500
59065,2023S006857,2,Eixample,10,Sant Antoni,323203,Sepúlveda ...,NaN,Dissabte,NaN,...,NaN,NaN,NaN,0096 0096,NaN,2023.0,4581394.65,429629.64,2.157306,41.379150
59066,2023S006857,2,Eixample,10,Sant Antoni,323203,Sepúlveda ...,NaN,Dissabte,NaN,...,NaN,NaN,NaN,0096 0096,NaN,2023.0,4581394.65,429629.64,2.157306,41.379150

In [12]:
df_accidents.duplicated().sum()

np.int64(0)

In [13]:
# Actualiza la columna existente Any con los valores de NK_Any cuando Any está vacía (NaN)
df_accidents["Any"] = df_accidents["Any"].combine_first(df_accidents["NK_Any"])

# Eliminar la columna redundante
df_accidents = df_accidents.drop(columns=["NK_Any"])

In [14]:
df_accidents.shape

(67488, 33)

In [15]:
# Tenemos la variable Num_postal duplicada con un espacion al final
[col for col in df_accidents.columns if "Num_postal" in col]

['Num_postal', 'Num_postal ', 'Num_postal_caption']

In [16]:
# Creamos columna unificada, priorizando la que ya se llama exactamente "Num_postal" que no tiene espacio
df_accidents["Num_postal"] = df_accidents["Num_postal"].combine_first(df_accidents["Num_postal "])

In [17]:
# Eliminamos variable redundante mal nombrada con un espacio al final
df_accidents.drop(columns=["Num_postal "], inplace=True)

In [18]:
df_accidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67488 entries, 0 to 67487
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Numero_expedient           67488 non-null  object
 1   Codi_districte             67488 non-null  int64
 2   Nom_districte              67488 non-null  object
 3   Codi_barri                 67488 non-null  object
 4   Nom_barri                  67488 non-null  object
 5   Codi_carrer                67488 non-null  int64
 6   Nom_carrer                 67486 non-null  object
 7   Num_postal                 27622 non-null  object
 8   Descripcio_dia_setmana     67488 non-null  object
 9   Dia_setmana                36570 non-null  object
 10  Descripcio_tipus_dia       36570 non-null  object
 11  Any                        67488 non-null  float64
 12  Mes_any                    67488 non-null  int64
 13  Nom_mes                    67488 non-null  object
 14  Dia_mes                    67488 non-null  int64
 15  Hora_dia                   67488 non-null  int64
 16  Descripcio_torn            67488 non-null  object
 17  Descripcio_causa_vianant   60423 non-null  object
 18  Numero_morts               59963 non-null  float64
 19  Numero_lesionats_lleus     66480 non-null  float64
 20  Numero_lesionats_greus     60193 non-null  float64
 21  Numero_victimes            66672 non-null  float64
 22  Numero_vehicles_implicats  67488 non-null  int64
 23  Coordenada_UTM_X           36570 non-null  object
 24  Coordenada_UTM_Y           36570 non-null  object
 25  Longitud                   44569 non-null  float64
 26  Latitud                    44569 non-null  float64
 27  Num_postal_caption         31953 non-null  object
 28  Coordenada_UTM_X_ED50      30918 non-null  object
 29  Coordenada_UTM_Y_ED50      30918 non-null  object
 30  Longitud_WGS84             22895 non-null  float64
 31  Latitud_WGS84              22895 non-null  float64
dtypes: float64(9), int64(6), object(17)
memory usage: 16.5+ MB

In [19]:
df_accidents.shape

(67488, 32)

In [20]:
df_accidents

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Numero_vehicles_implicats,Coordenada_UTM_X,Coordenada_UTM_Y,Longitud,Latitud,Num_postal_caption,Coordenada_UTM_X_ED50,Coordenada_UTM_Y_ED50,Longitud_WGS84,Latitud_WGS84
0,2017S008429,-1,Desconegut,-1,Desconegut,-1,Número 27 ...,Desconegut,Divendres,Dv,...,2,426936.65,4577079.15,2.125624,41.340045,NaN,NaN,NaN,NaN,NaN
1,2017S007316,-1,Desconegut,-1,Desconegut,-1,Número 3 Zona Franca / Número 50 Zona Franca ...,Desconegut,Divendres,Dv,...,2,426503.22,4577014.83,2.120452,41.339426,NaN,NaN,NaN,NaN,NaN
2,2017S010210,-1,Desconegut,-1,Desconegut,-1,Litoral (Besòs) ...,K128,Divendres,Dv,...,2,430450.5,4579358.49,2.167356,41.360886,NaN,NaN,NaN,NaN,NaN
3,2017S006364,-1,Desconegut,-1,Desconegut,-1,Número 3 Zona Franca ...,77-111,Divendres,Dv,...,2,426842.33,4576816.19,2.124529,41.337668,NaN,NaN,NaN,NaN,NaN
4,2017S004615,10,Sant Martí,64,el Camp de l'Arpa del Clot,226400,Las Navas de Tolosa ...,0323 0325,Dijous,Dj,...,3,"432006,95","4585503,52",2.185272,41.416365,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67483,2024S007547,2,Eixample,7,la Dreta de l'Eixample,169409,Corts Catalanes,603,Dimarts,NaN,...,1,NaN,NaN,NaN,NaN,NaN,4582460.824,430450.705,2.167002,41.388825
67484,2024S007548,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",143100,General Álvarez de Castro,2-4,Dissabte,NaN,...,1,NaN,NaN,NaN,NaN,NaN,4582233.737,431382.242,2.178169,41.386859
67485,2024S007549,3,Sants-Montjuïc,11,el Poble Sec,198804,Paral·lel,NaN,Dijous,NaN,...,1,NaN,NaN,NaN,NaN,NaN,4580940.29,428989.313,2.149703,41.375002
67486,2024S007550,3,Sants-Montjuïc,11,el Poble Sec,234001,Olímpic,1-3,Dilluns,NaN,...,1,NaN,NaN,NaN,NaN,NaN,4579426.054,429206.725,2.152479,41.361383
67487,2024S007551,1,Ciutat Vella,1,el Raval,701367,Raval,25X,Divendres,NaN,...,1,NaN,NaN,NaN,NaN,NaN,4581341.695,430668.432,2.169734,41.378764

In [21]:
# Filtrar filas donde ambas coordenadas WGS84 no son nulas
filtro_wgs84 = (
    df_accidents["Longitud_WGS84"].notna() &
    df_accidents["Latitud_WGS84"].notna()
)

# Contar registros por año con datos WGS84 completos
wgs84_por_año = df_accidents[filtro_wgs84].groupby("Any").size()

wgs84_por_año

Any
2021.0    7635
2023.0    7724
2024.0    7536
dtype: int64

In [22]:
df_accidents["Any"].value_counts().sort_index()

Any
2017.0    10339
2018.0     9936
2019.0    10027
2020.0     6268
2021.0     7659
2022.0     7999
2023.0     7724
2024.0     7536
Name: count, dtype: int64

In [25]:
df_accidents

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Numero_vehicles_implicats,Coordenada_UTM_X,Coordenada_UTM_Y,Longitud,Latitud,Num_postal_caption,Coordenada_UTM_X_ED50,Coordenada_UTM_Y_ED50,Longitud_WGS84,Latitud_WGS84
0,2017S008429,-1,Desconegut,-1,Desconegut,-1,Número 27 ...,Desconegut,Divendres,Dv,...,2,426936.65,4577079.15,2.125624,41.340045,NaN,NaN,NaN,NaN,NaN
1,2017S007316,-1,Desconegut,-1,Desconegut,-1,Número 3 Zona Franca / Número 50 Zona Franca ...,Desconegut,Divendres,Dv,...,2,426503.22,4577014.83,2.120452,41.339426,NaN,NaN,NaN,NaN,NaN
2,2017S010210,-1,Desconegut,-1,Desconegut,-1,Litoral (Besòs) ...,K128,Divendres,Dv,...,2,430450.5,4579358.49,2.167356,41.360886,NaN,NaN,NaN,NaN,NaN
3,2017S006364,-1,Desconegut,-1,Desconegut,-1,Número 3 Zona Franca ...,77-111,Divendres,Dv,...,2,426842.33,4576816.19,2.124529,41.337668,NaN,NaN,NaN,NaN,NaN
4,2017S004615,10,Sant Martí,64,el Camp de l'Arpa del Clot,226400,Las Navas de Tolosa ...,0323 0325,Dijous,Dj,...,3,"432006,95","4585503,52",2.185272,41.416365,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67483,2024S007547,2,Eixample,7,la Dreta de l'Eixample,169409,Corts Catalanes,603,Dimarts,NaN,...,1,NaN,NaN,NaN,NaN,NaN,4582460.824,430450.705,2.167002,41.388825
67484,2024S007548,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",143100,General Álvarez de Castro,2-4,Dissabte,NaN,...,1,NaN,NaN,NaN,NaN,NaN,4582233.737,431382.242,2.178169,41.386859
67485,2024S007549,3,Sants-Montjuïc,11,el Poble Sec,198804,Paral·lel,NaN,Dijous,NaN,...,1,NaN,NaN,NaN,NaN,NaN,4580940.29,428989.313,2.149703,41.375002
67486,2024S007550,3,Sants-Montjuïc,11,el Poble Sec,234001,Olímpic,1-3,Dilluns,NaN,...,1,NaN,NaN,NaN,NaN,NaN,4579426.054,429206.725,2.152479,41.361383
67487,2024S007551,1,Ciutat Vella,1,el Raval,701367,Raval,25X,Divendres,NaN,...,1,NaN,NaN,NaN,NaN,NaN,4581341.695,430668.432,2.169734,41.378764

In [28]:
mask_wgs84_1 = df_accidents["Longitud"].notna() & df_accidents["Latitud"].notna()
mask_wgs84_2 = df_accidents["Longitud_WGS84"].notna() & df_accidents["Latitud_WGS84"].notna()

mask_total = mask_wgs84_1 | mask_wgs84_2

num_registros = mask_total.sum()

print(f"Registros con coordenadas en WGS84 (en cualquiera de las dos versiones): {num_registros}")

Registros con coordenadas en WGS84 (en cualquiera de las dos versiones): 67464