In [1]:
import pandas as pd
from glob import glob
import os
from utils import cargar_y_unificar, limpiar_clave
import pickle

In [2]:
data_dir = '../data/raw/accidents_causa_vianant'
# Buscar todos los CSV de la carpeta
accident_files = sorted(glob(os.path.join(data_dir, "*.csv")))
accident_files

['../data/raw/accidents_causa_vianant/2017_accidents_gu_bcn.csv',
 '../data/raw/accidents_causa_vianant/2018_accidents_gu_bcn.csv',
 '../data/raw/accidents_causa_vianant/2019_accidents_gu_bcn.csv',
 '../data/raw/accidents_causa_vianant/2020_accidents_gu_bcn.csv',
 '../data/raw/accidents_causa_vianant/2021_accidents_gu_bcn.csv',
 '../data/raw/accidents_causa_vianant/2022_accidents_gu_bcn.csv',
 '../data/raw/accidents_causa_vianant/2023_accidents_gu_bcn.csv',
 '../data/raw/accidents_causa_vianant/2024_accidents_gu_bcn.csv']

In [3]:
# Leer y unir todos los archivos
df_accidents = pd.concat([pd.read_csv(file) for file in accident_files], ignore_index=True)
df_accidents

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Coordenada_UTM_Y,Longitud,Latitud,Num_postal,Num_postal_caption,NK_Any,Coordenada_UTM_X_ED50,Coordenada_UTM_Y_ED50,Longitud_WGS84,Latitud_WGS84
0,2017S008429,-1,Desconegut,-1,Desconegut,-1,Número 27 ...,Desconegut,Divendres,Dv,...,4577079.15,2.125624,41.340045,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017S007316,-1,Desconegut,-1,Desconegut,-1,Número 3 Zona Franca / Número 50 Zona Franca ...,Desconegut,Divendres,Dv,...,4577014.83,2.120452,41.339426,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017S010210,-1,Desconegut,-1,Desconegut,-1,Litoral (Besòs) ...,K128,Divendres,Dv,...,4579358.49,2.167356,41.360886,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017S006364,-1,Desconegut,-1,Desconegut,-1,Número 3 Zona Franca ...,77-111,Divendres,Dv,...,4576816.19,2.124529,41.337668,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017S004615,10,Sant Martí,64,el Camp de l'Arpa del Clot,226400,Las Navas de Tolosa ...,0323 0325,Dijous,Dj,...,"4585503,52",2.185272,41.416365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67483,2024S007547,2,Eixample,7,la Dreta de l'Eixample,169409,Corts Catalanes,NaN,Dimarts,NaN,...,NaN,NaN,NaN,603,NaN,2024.0,4582460.824,430450.705,2.167002,41.388825
67484,2024S007548,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",143100,General Álvarez de Castro,NaN,Dissabte,NaN,...,NaN,NaN,NaN,2-4,NaN,2024.0,4582233.737,431382.242,2.178169,41.386859
67485,2024S007549,3,Sants-Montjuïc,11,el Poble Sec,198804,Paral·lel,NaN,Dijous,NaN,...,NaN,NaN,NaN,NaN,NaN,2024.0,4580940.29,428989.313,2.149703,41.375002
67486,2024S007550,3,Sants-Montjuïc,11,el Poble Sec,234001,Olímpic,NaN,Dilluns,NaN,...,NaN,NaN,NaN,1-3,NaN,2024.0,4579426.054,429206.725,2.152479,41.361383
67487,2024S007551,1,Ciutat Vella,1,el Raval,701367,Raval,NaN,Divendres,NaN,...,NaN,NaN,NaN,25X,NaN,2024.0,4581341.695,430668.432,2.169734,41.378764

In [4]:
df_accidents['Nom_districte'].value_counts()

Nom_districte
Eixample               19131
Sant Martí              8345
Sants-Montjuïc          7380
Sarrià-Sant Gervasi     7288
Horta-Guinardó          4996
Les Corts               4637
Sant Andreu             4482
Nou Barris              3836
Ciutat Vella            3767
Gràcia                  3367
Desconegut               259
Name: count, dtype: int64

In [5]:
df_accidents.shape

(67488, 34)

In [6]:
df_accidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67488 entries, 0 to 67487
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Numero_expedient           67488 non-null  object
 1   Codi_districte             67488 non-null  int64
 2   Nom_districte              67488 non-null  object
 3   Codi_barri                 67488 non-null  object
 4   Nom_barri                  67488 non-null  object
 5   Codi_carrer                67488 non-null  int64
 6   Nom_carrer                 67486 non-null  object
 7   Num_postal                 10339 non-null  object
 8   Descripcio_dia_setmana     67488 non-null  object
 9   Dia_setmana                36570 non-null  object
 10  Descripcio_tipus_dia       36570 non-null  object
 11  Any                        20275 non-null  float64
 12  Mes_any                    67488 non-null  int64
 13  Nom_mes                    67488 non-null  object
 14  Dia_mes                    67488 non-null  int64
 15  Hora_dia                   67488 non-null  int64
 16  Descripcio_torn            67488 non-null  object
 17  Descripcio_causa_vianant   60423 non-null  object
 18  Numero_morts               59963 non-null  float64
 19  Numero_lesionats_lleus     66480 non-null  float64
 20  Numero_lesionats_greus     60193 non-null  float64
 21  Numero_victimes            66672 non-null  float64
 22  Numero_vehicles_implicats  67488 non-null  int64
 23  Coordenada_UTM_X           36570 non-null  object
 24  Coordenada_UTM_Y           36570 non-null  object
 25  Longitud                   44569 non-null  float64
 26  Latitud                    44569 non-null  float64
 27  Num_postal                 17283 non-null  object
 28  Num_postal_caption         31953 non-null  object
 29  NK_Any                     47213 non-null  float64
 30  Coordenada_UTM_X_ED50      30918 non-null  object
 31  Coordenada_UTM_Y_ED50      30918 non-null  object
 32  Longitud_WGS84             22895 non-null  float64
 33  Latitud_WGS84              22895 non-null  float64
dtypes: float64(10), int64(6), object(18)
memory usage: 17.5+ MB

In [7]:
df_accidents

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Coordenada_UTM_Y,Longitud,Latitud,Num_postal,Num_postal_caption,NK_Any,Coordenada_UTM_X_ED50,Coordenada_UTM_Y_ED50,Longitud_WGS84,Latitud_WGS84
0,2017S008429,-1,Desconegut,-1,Desconegut,-1,Número 27 ...,Desconegut,Divendres,Dv,...,4577079.15,2.125624,41.340045,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017S007316,-1,Desconegut,-1,Desconegut,-1,Número 3 Zona Franca / Número 50 Zona Franca ...,Desconegut,Divendres,Dv,...,4577014.83,2.120452,41.339426,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017S010210,-1,Desconegut,-1,Desconegut,-1,Litoral (Besòs) ...,K128,Divendres,Dv,...,4579358.49,2.167356,41.360886,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017S006364,-1,Desconegut,-1,Desconegut,-1,Número 3 Zona Franca ...,77-111,Divendres,Dv,...,4576816.19,2.124529,41.337668,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017S004615,10,Sant Martí,64,el Camp de l'Arpa del Clot,226400,Las Navas de Tolosa ...,0323 0325,Dijous,Dj,...,"4585503,52",2.185272,41.416365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67483,2024S007547,2,Eixample,7,la Dreta de l'Eixample,169409,Corts Catalanes,NaN,Dimarts,NaN,...,NaN,NaN,NaN,603,NaN,2024.0,4582460.824,430450.705,2.167002,41.388825
67484,2024S007548,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",143100,General Álvarez de Castro,NaN,Dissabte,NaN,...,NaN,NaN,NaN,2-4,NaN,2024.0,4582233.737,431382.242,2.178169,41.386859
67485,2024S007549,3,Sants-Montjuïc,11,el Poble Sec,198804,Paral·lel,NaN,Dijous,NaN,...,NaN,NaN,NaN,NaN,NaN,2024.0,4580940.29,428989.313,2.149703,41.375002
67486,2024S007550,3,Sants-Montjuïc,11,el Poble Sec,234001,Olímpic,NaN,Dilluns,NaN,...,NaN,NaN,NaN,1-3,NaN,2024.0,4579426.054,429206.725,2.152479,41.361383
67487,2024S007551,1,Ciutat Vella,1,el Raval,701367,Raval,NaN,Divendres,NaN,...,NaN,NaN,NaN,25X,NaN,2024.0,4581341.695,430668.432,2.169734,41.378764

In [8]:
df_accidents.isnull().sum().sort_values(ascending=False)

Num_postal                   57149
Num_postal                   50205
Any                          47213
Latitud_WGS84                44593
Longitud_WGS84               44593
Coordenada_UTM_Y_ED50        36570
Coordenada_UTM_X_ED50        36570
Num_postal_caption           35535
Coordenada_UTM_X             30918
Coordenada_UTM_Y             30918
Descripcio_tipus_dia         30918
Dia_setmana                  30918
Longitud                     22919
Latitud                      22919
NK_Any                       20275
Numero_morts                  7525
Numero_lesionats_greus        7295
Descripcio_causa_vianant      7065
Numero_lesionats_lleus        1008
Numero_victimes                816
Nom_carrer                       2
Numero_expedient                 0
Codi_districte                   0
Hora_dia                         0
Descripcio_torn                  0
Descripcio_dia_setmana           0
Nom_districte                    0
Codi_carrer                      0
Dia_mes                          0
Nom_mes                          0
Mes_any                          0
Nom_barri                        0
Codi_barri                       0
Numero_vehicles_implicats        0
dtype: int64

In [9]:
df_accidents.describe().T

,count,mean,std,min,25%,50%,75%,max
Codi_districte,67488.0,4.868243,3.013772,-1.000000,2.000000,4.000000,7.000000,10.000000
Codi_carrer,67488.0,247783.118169,200040.713513,-1.000000,115400.000000,191204.000000,320908.000000,701918.000000
Any,20275.0,2017.490062,0.499914,2017.000000,2017.000000,2017.000000,2018.000000,2018.000000
Mes_any,67488.0,6.534554,3.462213,1.000000,4.000000,7.000000,10.000000,12.000000
Dia_mes,67488.0,15.717150,8.779916,1.000000,8.000000,16.000000,23.000000,31.000000
Hora_dia,67488.0,13.828266,5.320445,0.000000,10.000000,14.000000,18.000000,23.000000
Numero_morts,59963.0,0.002285,0.047745,0.000000,0.000000,0.000000,0.000000,1.000000
Numero_lesionats_lleus,66480.0,1.153309,0.754789,0.000000,1.000000,1.000000,1.000000,25.000000
Numero_lesionats_greus,60193.0,0.027345,0.175739,0.000000,0.000000,0.000000,0.000000,6.000000
Numero_victimes,66672.0,1.176731,0.749221,0.000000,1.000000,1.000000,1.000000,26.000000
Numero_vehicles_implicats,67488.0,1.886898,0.717799,0.000000,2.000000,2.000000,2.000000,18.000000
Longitud,44569.0,3.128052,45.621050,-1.488576,2.145109,2.163811,2.180220,2188.000000
Latitud,44569.0,59.934192,875.557565,0.000009,41.385887,41.397111,41.411475,41414.000000
NK_Any,47213.0,2021.417957,1.751577,2019.000000,2020.000000,2021.000000,2023.000000,2024.000000
Longitud_WGS84,22895.0,2.162846,0.024417,2.058047,2.144797,2.163447,2.180530,2.223673
Latitud_WGS84,22895.0,41.400521,0.022460,41.322721,41.385918,41.397848,41.413622,41.467466

In [10]:
df_accidents['Dia_setmana'].value_counts()

Dia_setmana
Dv    5122
Dj    4923
Dc    4915
Dm    4879
Dl    4530
Ds    3338
Dg    2595
4     1104
5     1032
3     1023
1      972
2      933
6      686
7      518
Name: count, dtype: int64

In [11]:
# Ver si hay valores duplicados del numero de expediente
duplicados = df_accidents[df_accidents["Numero_expedient"].duplicated()]
duplicados

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Coordenada_UTM_Y,Longitud,Latitud,Num_postal,Num_postal_caption,NK_Any,Coordenada_UTM_X_ED50,Coordenada_UTM_Y_ED50,Longitud_WGS84,Latitud_WGS84
5800,2017S003286,3,Sants-Montjuïc,13,la Marina de Port,109906,Energia ...,0001X0001X,Dilluns,Dl,...,"4579006,9",2.136744,41.357598,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6492,2017S008856,10,Sant Martí,71,Provençals del Poblenou,30409,Diagonal / Bac de Roda ...,0100 0108,Dijous,Dj,...,"4584557,54",2.203962,41.407568,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6979,2017S003750,2,Eixample,7,la Dreta de l'Eixample,357001,Bergara ...,0014 0014,Dijous,Dj,...,"4582179,48",2.168836,41.386306,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9211,2017S004447,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,701278,Taulat ...,0136 0136,Divendres,Dv,...,"4583913,96",2.209813,41.402218,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10655,2018S003156,3,Sants-Montjuïc,16,la Bordeta,169409,Corts Catalanes ...,NaN,Dimarts,Dm,...,4579751.39,2.133801,41.364177,111-119,NaN,NaN,NaN,NaN,NaN,NaN
10784,2018S002285,3,Sants-Montjuïc,16,la Bordeta,89707,Constitució ...,NaN,Dijous,Dj,...,4580251.36,2.132499,41.368671,155,NaN,NaN,NaN,NaN,NaN,NaN
11548,2018S002968,3,Sants-Montjuïc,17,Sants - Badal,187207,Madrid ...,NaN,Dimecres,Dc,...,4581285.13,2.126816,41.377939,68,NaN,NaN,NaN,NaN,NaN,NaN
11591,2018S009504,2,Eixample,10,Sant Antoni,127704,Floridablanca / Viladomat ...,NaN,Dijous,Dj,...,4581335.47,2.158684,41.378630,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12870,2018S005992,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",177101,Laietana ...,NaN,Dijous,Dj,...,4582187.93,2.175646,41.386431,46,NaN,NaN,NaN,NaN,NaN,NaN
13124,2018S001774,4,Les Corts,20,la Maternitat i Sant Ramon,144601,Diagonal ...,NaN,Diumenge,Dg,...,4582337.48,2.125516,41.387409,629,NaN,NaN,NaN,NaN,NaN,NaN
14651,2018S000261,5,Sarrià-Sant Gervasi,23,Sarrià,305201,Sant Joan Bosco / Maria Auxiliadora ...,NaN,Dijous,Dj,...,4583076.17,2.127990,41.394081,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16010,2018S002344,5,Sarrià-Sant Gervasi,26,Sant Gervasi - Galvany,143904,General Mitre ...,NaN,Dissabte,Ds,...,4583745.01,2.135246,41.400160,92-94,NaN,NaN,NaN,NaN,NaN,NaN
17263,2018S001500,6,Gràcia,31,la Vila de Gràcia,290206,Torrent de les Flors / Rovira i Trias ...,NaN,Dissabte,Ds,...,4584552.91,2.158799,41.407612,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17379,2018S000183,6,Gràcia,32,el Camp d'en Grassot i Gràcia Nova,356304,Taxdirt / Ventalló ...,NaN,Dilluns,Dl,...,4584642.04,2.164942,41.408460,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30935,2020S000638,5,Sarrià-Sant Gervasi,51-5-26,Sant Gervasi - Galvany,344101,Gràcia,NaN,Dilluns,1,...,4583295.6,2.149556,41.396216,NaN,0051 0051,2020.0,NaN,NaN,NaN,NaN
31076,2020S000778,9,Sant Andreu,91-9-63,Navas,209900,Meridiana,NaN,Dijous,4,...,4585841.6,2.186612,41.419417,NaN,0235 0235,2020.0,NaN,NaN,NaN,NaN
31253,2020S000956,2,Eixample,23-2-8,l'Antiga Esquerra de l'Eixample,350308,València,NaN,Dissabte,6,...,4582643.19,2.160104,41.390417,NaN,0211 0211,2020.0,NaN,NaN,NaN,NaN
33958,2020S003665,2,Eixample,25-2-6,la Sagrada Família,178308,Lepant,NaN,Dijous,4,...,4584077.09,2.178158,41.403463,NaN,0258 0258,2020.0,NaN,NaN,NaN,NaN
34772,2020S004479,5,Sarrià-Sant Gervasi,53-5-25,Sant Gervasi - la Bonanova,701268,Dalt (Llobregat),NaN,Dimarts,2,...,4585391.51,2.136151,41.414995,NaN,940000,2020.0,NaN,NaN,NaN,NaN
34883,2020S004590,8,Nou Barris,82-8-49,Canyelles,120807,Favència,NaN,Dijous,4,...,4588348.41,2.166402,41.441853,NaN,0041 0045,2020.0,NaN,NaN,NaN,NaN
35587,2020S005294,4,Les Corts,42-4-20,la Maternitat i Sant Ramon,187207,Madrid,NaN,Dimecres,3,...,4581210.7,2.125031,41.377253,NaN,0039 0041,2020.0,NaN,NaN,NaN,NaN
39132,2021S000395,6,Gràcia,28,Vallcarca i els Penitents,123408,Lesseps,NaN,Dimarts,NaN,...,NaN,NaN,NaN,NaN,0021X0021X,2021.0,429024.35,4584481.54,2.149706,41.406900
39836,2021S000847,2,Eixample,6,la Sagrada Família,90502,Còrsega,NaN,Dijous,NaN,...,NaN,NaN,NaN,NaN,0532 0532,2021.0,430891.22,4584360.4,2.172053,41.405971
42346,2021S001332,10,Sant Martí,64,el Camp de l'Arpa del Clot,161407,Indústria,NaN,Dimarts,NaN,...,NaN,NaN,NaN,NaN,0279 0281,2021.0,431670.92,4585357.49,2.181268,41.415019
42627,2021S002982,2,Eixample,8,l'Antiga Esquerra de l'Eixample,169409,Corts Catalanes,NaN,Dissabte,NaN,...,NaN,NaN,NaN,NaN,0583 0583,2021.0,430080.36,4582095.48,2.162615,41.385502
43329,2021S001951,10,Sant Martí,65,el Clot,161101,Independència,NaN,Dijous,NaN,...,NaN,NaN,NaN,NaN,0243 0243,2021.0,432003.59,4584366.47,2.185360,41.406121
43982,2021S005130,6,Gràcia,28,Vallcarca i els Penitents,158107,Vallcarca,NaN,Dijous,NaN,...,NaN,NaN,NaN,NaN,0133 0147,2021.0,428461.6,4585247.52,2.142883,41.413749
45517,2022S000750,2,Eixample,7,la Dreta de l'Eixample,169409,Corts Catalanes ...,NaN,Dimarts,NaN,...,NaN,2.165224,41.386804,NaN,0602 0602,2022.0,430299.85,4582237.63,NaN,NaN
48105,2022S000364,7,Horta-Guinardó,33,el Baix Guinardó,76807,Sardenya / Providència ...,NaN,Dissabte,NaN,...,NaN,2.163939,41.410488,NaN,0494 0494,2022.0,430217.78,4584868.03,NaN,NaN
48476,2022S007820,2,Eixample,8,l'Antiga Esquerra de l'Eixample,349706,Comte d'Urgell / Sarrià ...,NaN,Dimecres,NaN,...,NaN,2.148272,41.389882,NaN,0217 0223,2022.0,428885.89,4582593.13,NaN,NaN
49388,2022S001333,1,Ciutat Vella,1,el Raval,76501,Cera / Reina Amàlia ...,NaN,Dissabte,NaN,...,NaN,2.165245,41.378098,NaN,0040 0040,2022.0,430292.31,4581271.11,NaN,NaN
49507,2022S002608,2,Eixample,9,la Nova Esquerra de l'Eixample,350308,València ...,NaN,Dimarts,NaN,...,NaN,2.148623,41.381494,NaN,0064 0066,2022.0,428906.06,4581661.62,NaN,NaN
49527,2022S007071,2,Eixample,9,la Nova Esquerra de l'Eixample,54509,Calàbria / Diputació ...,NaN,Divendres,NaN,...,NaN,2.153920,41.380520,NaN,0115 0117,2022.0,429347.93,4581549.1,NaN,NaN
50367,2022S003249,10,Sant Martí,71,Provençals del Poblenou,169409,Corts Catalanes ...,NaN,Dissabte,NaN,...,NaN,2.204231,41.415753,NaN,1092 1094,2022.0,433590.68,4585420.82,NaN,NaN
50627,2022S000411,2,Eixample,6,la Sagrada Família,68900,Cartagena ...,NaN,Dilluns,NaN,...,NaN,2.178533,41.407851,NaN,0241 0241,2022.0,431434.74,4584563.62,NaN,NaN
50717,2022S007743,2,Eixample,5,el Fort Pienc,197302,Marina ...,NaN,Divendres,NaN,...,NaN,2.179451,41.400151,NaN,0191 0191,2022.0,431503.37,4583708.04,NaN,NaN
51395,2022S000209,1,Ciutat Vella,2,el Barri Gòtic,82901,Colom ...,NaN,Divendres,NaN,...,NaN,2.181484,41.381019,NaN,0001 0001,2022.0,431653.31,4581582.41,NaN,NaN
53302,2023S001079,6,Gràcia,31,la Vila de Gràcia,267000,Riera de Cassoles / Bretón de los Herreros ...,NaN,Dimecres,NaN,...,NaN,NaN,NaN,0008 0008,NaN,2023.0,4583923.03,429116.73,2.150877,41.401878
56937,2023S004724,10,Sant Martí,67,la Vila Olímpica del Poblenou,110009,Ramon Turró ...,NaN,Divendres,NaN,...,NaN,NaN,NaN,0037 0037,NaN,2023.0,4582848.16,432648.07,2.193239,41.392500
59066,2023S006857,2,Eixample,10,Sant Antoni,323203,Sepúlveda ...,NaN,Dissabte,NaN,...,NaN,NaN,NaN,0096 0096,NaN,2023.0,4581394.65,429629.64,2.157306,41.379150

In [12]:
# Encontrar los expedientes duplicados (que aparecen más de una vez)
duplicados_ids = df_accidents["Numero_expedient"][df_accidents["Numero_expedient"].duplicated(keep=False)]
duplicados_ids

84       2017S008856
3079     2017S003750
5222     2017S004447
5799     2017S003286
5800     2017S003286
              ...
53302    2023S001079
56936    2023S004724
56937    2023S004724
59065    2023S006857
59066    2023S006857
Name: Numero_expedient, Length: 80, dtype: object

In [13]:
# Filtrar todos los registros con los expedientes duplicados
expedientes_duplicados= df_accidents[df_accidents["Numero_expedient"].isin(duplicados_ids)]
expedientes_duplicados.sort_values("Numero_expedient")

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Coordenada_UTM_Y,Longitud,Latitud,Num_postal,Num_postal_caption,NK_Any,Coordenada_UTM_X_ED50,Coordenada_UTM_Y_ED50,Longitud_WGS84,Latitud_WGS84
5799,2017S003286,3,Sants-Montjuïc,13,la Marina de Port,109906,Energia ...,0001X0001X,Dilluns,Dl,...,"4579006,9",2.136744,41.357598,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5800,2017S003286,3,Sants-Montjuïc,13,la Marina de Port,109906,Energia ...,0001X0001X,Dilluns,Dl,...,"4579006,9",2.136744,41.357598,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3079,2017S003750,2,Eixample,7,la Dreta de l'Eixample,357001,Bergara ...,0014 0014,Dijous,Dj,...,"4582179,48",2.168836,41.386306,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6979,2017S003750,2,Eixample,7,la Dreta de l'Eixample,357001,Bergara ...,0014 0014,Dijous,Dj,...,"4582179,48",2.168836,41.386306,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5222,2017S004447,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,701278,Taulat ...,0136 0136,Divendres,Dv,...,"4583913,96",2.209813,41.402218,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53302,2023S001079,6,Gràcia,31,la Vila de Gràcia,267000,Riera de Cassoles / Bretón de los Herreros ...,NaN,Dimecres,NaN,...,NaN,NaN,NaN,0008 0008,NaN,2023.0,4583923.03,429116.73,2.150877,41.401878
56936,2023S004724,10,Sant Martí,67,la Vila Olímpica del Poblenou,110009,Ramon Turró ...,NaN,Divendres,NaN,...,NaN,NaN,NaN,0037 0037,NaN,2023.0,4582848.16,432648.07,2.193239,41.392500
56937,2023S004724,10,Sant Martí,67,la Vila Olímpica del Poblenou,110009,Ramon Turró ...,NaN,Divendres,NaN,...,NaN,NaN,NaN,0037 0037,NaN,2023.0,4582848.16,432648.07,2.193239,41.392500
59065,2023S006857,2,Eixample,10,Sant Antoni,323203,Sepúlveda ...,NaN,Dissabte,NaN,...,NaN,NaN,NaN,0096 0096,NaN,2023.0,4581394.65,429629.64,2.157306,41.379150
59066,2023S006857,2,Eixample,10,Sant Antoni,323203,Sepúlveda ...,NaN,Dissabte,NaN,...,NaN,NaN,NaN,0096 0096,NaN,2023.0,4581394.65,429629.64,2.157306,41.379150

In [14]:
col_fijas = [c for c in df_accidents.columns if c != 'Descripcio_causa_vianant']

df_accidents = (
    df_accidents
    .groupby("Numero_expedient", as_index=False)
    .agg({
        **{col: 'first' for col in col_fijas if col != "Numero_expedient"},
        'Descripcio_causa_vianant': lambda x: (
            pd.NA if x.isna().all() 
            else ", ".join(sorted(set(v for v in x if pd.notna(v) and str(v).strip() != "")))
        )
    })
)

In [15]:
df_accidents

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Longitud,Latitud,Num_postal,Num_postal_caption,NK_Any,Coordenada_UTM_X_ED50,Coordenada_UTM_Y_ED50,Longitud_WGS84,Latitud_WGS84,Descripcio_causa_vianant
0,2017S000001,5,Sarrià-Sant Gervasi,26,Sant Gervasi - Galvany,187105,VIA AUGUSTA ...,0063 0063,Diumenge,Dg,...,2.151330,41.400771,None,None,NaN,None,None,NaN,NaN,No és causa del vianant
1,2017S000002,2,Eixample,5,el Fort Pienc,197302,GV CORTS CATALANES ...,0120 0120,Diumenge,Dg,...,2.182376,41.399680,None,None,NaN,None,None,NaN,NaN,No és causa del vianant
2,2017S000003,7,Horta-Guinardó,33,el Baix Guinardó,265402,RDA GUINARDÓ ...,0000 0000,Diumenge,Dg,...,2.166464,41.412769,None,None,NaN,None,None,NaN,NaN,No és causa del vianant
3,2017S000004,2,Eixample,6,la Sagrada Família,89004,BALMES / Rosselló ...,0531 0531,Diumenge,Dg,...,2.157359,41.393310,None,None,NaN,None,None,NaN,NaN,No és causa del vianant
4,2017S000005,10,Sant Martí,66,el Parc i la Llacuna del Poblenou,243206,PALLARS ...,0091 0091,Diumenge,Dg,...,2.193249,41.397908,None,None,NaN,None,None,NaN,NaN,No és causa del vianant
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67443,2024S007547,2,Eixample,7,la Dreta de l'Eixample,169409,Corts Catalanes,None,Dimarts,None,...,NaN,NaN,603,None,2024.0,4582460.824,430450.705,2.167002,41.388825,Altres
67444,2024S007548,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",143100,General Álvarez de Castro,None,Dissabte,None,...,NaN,NaN,2-4,None,2024.0,4582233.737,431382.242,2.178169,41.386859,<NA>
67445,2024S007549,3,Sants-Montjuïc,11,el Poble Sec,198804,Paral·lel,None,Dijous,None,...,NaN,NaN,None,None,2024.0,4580940.29,428989.313,2.149703,41.375002,<NA>
67446,2024S007550,3,Sants-Montjuïc,11,el Poble Sec,234001,Olímpic,None,Dilluns,None,...,NaN,NaN,1-3,None,2024.0,4579426.054,429206.725,2.152479,41.361383,<NA>
67447,2024S007551,1,Ciutat Vella,1,el Raval,701367,Raval,None,Divendres,None,...,NaN,NaN,25X,None,2024.0,4581341.695,430668.432,2.169734,41.378764,<NA>

In [16]:
# Comprobamos que ya no hay expedientes duplicados
df_accidents[df_accidents["Numero_expedient"].isin(duplicados_ids)]

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Longitud,Latitud,Num_postal,Num_postal_caption,NK_Any,Coordenada_UTM_X_ED50,Coordenada_UTM_Y_ED50,Longitud_WGS84,Latitud_WGS84,Descripcio_causa_vianant
2887,2017S003286,3,Sants-Montjuïc,13,la Marina de Port,109906,Energia ...,0001X0001X,Dilluns,Dl,...,2.136744,41.357598,None,None,NaN,None,None,NaN,NaN,"Creuar per fora pas de vianants, Transitar a p..."
3348,2017S003750,2,Eixample,7,la Dreta de l'Eixample,357001,Bergara ...,0014 0014,Dijous,Dj,...,2.168836,41.386306,None,None,NaN,None,None,NaN,NaN,"Altres, Desobeir el senyal del semàfor"
4041,2017S004447,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,701278,Taulat ...,0136 0136,Divendres,Dv,...,2.209813,41.402218,None,None,NaN,None,None,NaN,NaN,"Creuar per fora pas de vianants, Transitar a p..."
8413,2017S008856,10,Sant Martí,71,Provençals del Poblenou,30409,Diagonal / Bac de Roda ...,0100 0108,Dijous,Dj,...,2.203962,41.407568,None,None,NaN,None,None,NaN,NaN,"Altres, Desobeir el senyal del semàfor"
10517,2018S000183,6,Gràcia,32,el Camp d'en Grassot i Gràcia Nova,356304,Taxdirt / Ventalló ...,None,Dilluns,Dl,...,2.164942,41.408460,None,None,NaN,None,None,NaN,NaN,"Altres, Transitar a peu per la calçada"
10594,2018S000261,5,Sarrià-Sant Gervasi,23,Sarrià,305201,Sant Joan Bosco / Maria Auxiliadora ...,None,Dijous,Dj,...,2.127990,41.394081,None,None,NaN,None,None,NaN,NaN,"Altres, Desobeir el senyal del semàfor"
11819,2018S001500,6,Gràcia,31,la Vila de Gràcia,290206,Torrent de les Flors / Rovira i Trias ...,None,Dissabte,Ds,...,2.158799,41.407612,None,None,NaN,None,None,NaN,NaN,"Altres, Creuar per fora pas de vianants"
12093,2018S001774,4,Les Corts,20,la Maternitat i Sant Ramon,144601,Diagonal ...,None,Diumenge,Dg,...,2.125516,41.387409,629,None,NaN,None,None,NaN,NaN,"Creuar per fora pas de vianants, Desobeir el s..."
12602,2018S002285,3,Sants-Montjuïc,16,la Bordeta,89707,Constitució ...,None,Dijous,Dj,...,2.132499,41.368671,155,None,NaN,None,None,NaN,NaN,"Creuar per fora pas de vianants, Transitar a p..."
12660,2018S002344,5,Sarrià-Sant Gervasi,26,Sant Gervasi - Galvany,143904,General Mitre ...,None,Dissabte,Ds,...,2.135246,41.400160,92-94,None,NaN,None,None,NaN,NaN,"Creuar per fora pas de vianants, Desobeir el s..."
13282,2018S002968,3,Sants-Montjuïc,17,Sants - Badal,187207,Madrid ...,None,Dimecres,Dc,...,2.126816,41.377939,68,None,NaN,None,None,NaN,NaN,"Creuar per fora pas de vianants, Transitar a p..."
13467,2018S003156,3,Sants-Montjuïc,16,la Bordeta,169409,Corts Catalanes ...,None,Dimarts,Dm,...,2.133801,41.364177,111-119,None,NaN,None,None,NaN,NaN,"Altres, Desobeir el senyal del semàfor"
16288,2018S005992,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",177101,Laietana ...,None,Dijous,Dj,...,2.175646,41.386431,46,None,NaN,None,None,NaN,NaN,"Creuar per fora pas de vianants, Desobeir el s..."
19792,2018S009504,2,Eixample,10,Sant Antoni,127704,Floridablanca / Viladomat ...,None,Dijous,Dj,...,2.158684,41.378630,None,None,NaN,None,None,NaN,NaN,"Altres, Desobeir el senyal del semàfor"
30920,2020S000638,5,Sarrià-Sant Gervasi,51-5-26,Sant Gervasi - Galvany,344101,Gràcia,None,Dilluns,1,...,2.149556,41.396216,None,0051 0051,2020.0,None,None,NaN,NaN,"Creuar per fora pas de vianants, Desobeir el s..."
31060,2020S000778,9,Sant Andreu,91-9-63,Navas,209900,Meridiana,None,Dijous,4,...,2.186612,41.419417,None,0235 0235,2020.0,None,None,NaN,NaN,"Altres, Creuar per fora pas de vianants"
31236,2020S000956,2,Eixample,23-2-8,l'Antiga Esquerra de l'Eixample,350308,València,None,Dissabte,6,...,2.160104,41.390417,None,0211 0211,2020.0,None,None,NaN,NaN,"Creuar per fora pas de vianants, Transitar a p..."
33940,2020S003665,2,Eixample,25-2-6,la Sagrada Família,178308,Lepant,None,Dijous,4,...,2.178158,41.403463,None,0258 0258,2020.0,None,None,NaN,NaN,"Altres, Desobeir el senyal del semàfor"
34753,2020S004479,5,Sarrià-Sant Gervasi,53-5-25,Sant Gervasi - la Bonanova,701268,Dalt (Llobregat),None,Dimarts,2,...,2.136151,41.414995,None,940000,2020.0,None,None,NaN,NaN,"Altres, Transitar a peu per la calçada"
34863,2020S004590,8,Nou Barris,82-8-49,Canyelles,120807,Favència,None,Dijous,4,...,2.166402,41.441853,None,0041 0045,2020.0,None,None,NaN,NaN,"Altres, Desobeir el senyal del semàfor"
35566,2020S005294,4,Les Corts,42-4-20,la Maternitat i Sant Ramon,187207,Madrid,None,Dimecres,3,...,2.125031,41.377253,None,0039 0041,2020.0,None,None,NaN,NaN,"Altres, Desobeir el senyal del semàfor"
36943,2021S000395,6,Gràcia,28,Vallcarca i els Penitents,123408,Lesseps,None,Dimarts,None,...,NaN,NaN,None,0021X0021X,2021.0,429024.35,4584481.54,2.149706,41.406900,"Altres, Desobeir el senyal del semàfor"
37394,2021S000847,2,Eixample,6,la Sagrada Família,90502,Còrsega,None,Dijous,None,...,NaN,NaN,None,0532 0532,2021.0,430891.22,4584360.4,2.172053,41.405971,"Creuar per fora pas de vianants, Transitar a p..."
37879,2021S001332,10,Sant Martí,64,el Camp de l'Arpa del Clot,161407,Indústria,None,Dimarts,None,...,NaN,NaN,None,0279 0281,2021.0,431670.92,4585357.49,2.181268,41.415019,"Creuar per fora pas de vianants, Transitar a p..."
38495,2021S001951,10,Sant Martí,65,el Clot,161101,Independència,None,Dijous,None,...,NaN,NaN,None,0243 0243,2021.0,432003.59,4584366.47,2.185360,41.406121,"Creuar per fora pas de vianants, Desobeir el s..."
39522,2021S002982,2,Eixample,8,l'Antiga Esquerra de l'Eixample,169409,Corts Catalanes,None,Dissabte,None,...,NaN,NaN,None,0583 0583,2021.0,430080.36,4582095.48,2.162615,41.385502,"Creuar per fora pas de vianants, Transitar a p..."
41668,2021S005130,6,Gràcia,28,Vallcarca i els Penitents,158107,Vallcarca,None,Dijous,None,...,NaN,NaN,None,0133 0147,2021.0,428461.6,4585247.52,2.142883,41.413749,"Altres, Desobeir el senyal del semàfor"
44410,2022S000209,1,Ciutat Vella,2,el Barri Gòtic,82901,Colom ...,None,Divendres,None,...,2.181484,41.381019,None,0001 0001,2022.0,431653.31,4581582.41,NaN,NaN,"Altres, Desobeir el senyal del semàfor"
44564,2022S000364,7,Horta-Guinardó,33,el Baix Guinardó,76807,Sardenya / Providència ...,None,Dissabte,None,...,2.163939,41.410488,None,0494 0494,2022.0,430217.78,4584868.03,NaN,NaN,"Altres, Desobeir el senyal del semàfor"
44611,2022S000411,2,Eixample,6,la Sagrada Família,68900,Cartagena ...,None,Dilluns,None,...,2.178533,41.407851,None,0241 0241,2022.0,431434.74,4584563.62,NaN,NaN,"Altres, Desobeir el senyal del semàfor"
44949,2022S000750,2,Eixample,7,la Dreta de l'Eixample,169409,Corts Catalanes ...,None,Dimarts,None,...,2.165224,41.386804,None,0602 0602,2022.0,430299.85,4582237.63,NaN,NaN,"Altres, Transitar a peu per la calçada"
45528,2022S001333,1,Ciutat Vella,1,el Raval,76501,Cera / Reina Amàlia ...,None,Dissabte,None,...,2.165245,41.378098,None,0040 0040,2022.0,430292.31,4581271.11,NaN,NaN,"Altres, Transitar a peu per la calçada"
46801,2022S002608,2,Eixample,9,la Nova Esquerra de l'Eixample,350308,València ...,None,Dimarts,None,...,2.148623,41.381494,None,0064 0066,2022.0,428906.06,4581661.62,NaN,NaN,"Altres, Desobeir el senyal del semàfor"
47440,2022S003249,10,Sant Martí,71,Provençals del Poblenou,169409,Corts Catalanes ...,None,Dissabte,None,...,2.204231,41.415753,None,1092 1094,2022.0,433590.68,4585420.82,NaN,NaN,"Altres, Creuar per fora pas de vianants"
51252,2022S007071,2,Eixample,9,la Nova Esquerra de l'Eixample,54509,Calàbria / Diputació ...,None,Divendres,None,...,2.153920,41.380520,None,0115 0117,2022.0,429347.93,4581549.1,NaN,NaN,"Altres, Desobeir el senyal del semàfor"
51919,2022S007743,2,Eixample,5,el Fort Pienc,197302,Marina ...,None,Divendres,None,...,2.179451,41.400151,None,0191 0191,2022.0,431503.37,4583708.04,NaN,NaN,"Creuar per fora pas de vianants, Desobeir altr..."
51995,2022S007820,2,Eixample,8,l'Antiga Esquerra de l'Eixample,349706,Comte d'Urgell / Sarrià ...,None,Dimecres,None,...,2.148272,41.389882,None,0217 0223,2022.0,428885.89,4582593.13,NaN,NaN,"Creuar per fora pas de vianants, Transitar a p..."
53264,2023S001079,6,Gràcia,31,la Vila de Gràcia,267000,Riera de Cassoles / Bretón de los Herreros ...,None,Dimecres,None,...,NaN,NaN,0008 0008,None,2023.0,4583923.03,429116.73,2.150877,41.401878,"Altres, Desobeir el senyal del semàfor"
56898,2023S004724,10,Sant Martí,67,la Vila Olímpica del Poblenou,110009,Ramon Turró ...,None,Divendres,None,...,NaN,NaN,0037 0037,None,2023.0,4582848.16,432648.07,2.193239,41.392500,"Creuar per fora pas de vianants, Transitar a p..."
59026,2023S006857,2,Eixample,10,Sant Antoni,323203,Sepúlveda ...,None,Dissabte,None,...,NaN,NaN,0096 0096,None,2023.0,4581394.65,429629.64,2.157306,41.379150,"Creuar per fora pas de vianants, Transitar a p..."

In [17]:
df_accidents.duplicated().sum()

np.int64(0)

In [18]:
# Actualiza la columna existente Any con los valores de NK_Any cuando Any está vacía (NaN)
df_accidents["Any"] = df_accidents["Any"].combine_first(df_accidents["NK_Any"])

# Eliminar la columna redundante
df_accidents = df_accidents.drop(columns=["NK_Any"])

In [19]:
df_accidents.shape

(67448, 33)

In [20]:
df_accidents[['Num_postal', 'Num_postal ', 'Num_postal_caption']]

      Num_postal Num_postal  Num_postal_caption
0      0063 0063        None               None
1      0120 0120        None               None
2      0000 0000        None               None
3      0531 0531        None               None
4      0091 0091        None               None
...          ...         ...                ...
67443       None         603               None
67444       None         2-4               None
67445       None        None               None
67446       None         1-3               None
67447       None         25X               None

[67448 rows x 3 columns]

In [21]:
df_accidents[df_accidents[['Num_postal', 'Num_postal ', 'Num_postal_caption']].notna().all(axis=1)]

Empty DataFrame
Columns: [Numero_expedient, Codi_districte, Nom_districte, Codi_barri, Nom_barri, Codi_carrer, Nom_carrer, Num_postal, Descripcio_dia_setmana, Dia_setmana, Descripcio_tipus_dia, Any, Mes_any, Nom_mes, Dia_mes, Hora_dia, Descripcio_torn, Numero_morts, Numero_lesionats_lleus, Numero_lesionats_greus, Numero_victimes, Numero_vehicles_implicats, Coordenada_UTM_X, Coordenada_UTM_Y, Longitud, Latitud, Num_postal , Num_postal_caption, Coordenada_UTM_X_ED50, Coordenada_UTM_Y_ED50, Longitud_WGS84, Latitud_WGS84, Descripcio_causa_vianant]
Index: []

[0 rows x 33 columns]

In [22]:
# Tenemos 3 variables redundates del numero postal
[col for col in df_accidents.columns if "Num_postal" in col]

['Num_postal', 'Num_postal ', 'Num_postal_caption']

In [23]:
# Creamos columna unificada, priorizando la que ya se llama exactamente "Num_postal" que no tiene espacio
df_accidents["Num_postal"] = df_accidents["Num_postal"].combine_first(df_accidents["Num_postal "])
df_accidents["Num_postal"] = df_accidents["Num_postal"].combine_first(df_accidents["Num_postal_caption"])

In [24]:
# Eliminamos variables redundante mal nombrada con un espacio al final
df_accidents.drop(columns=['Num_postal ','Num_postal_caption'], inplace=True)

In [25]:
df_accidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67448 entries, 0 to 67447
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Numero_expedient           67448 non-null  object
 1   Codi_districte             67448 non-null  int64
 2   Nom_districte              67448 non-null  object
 3   Codi_barri                 67448 non-null  object
 4   Nom_barri                  67448 non-null  object
 5   Codi_carrer                67448 non-null  int64
 6   Nom_carrer                 67446 non-null  object
 7   Num_postal                 59539 non-null  object
 8   Descripcio_dia_setmana     67448 non-null  object
 9   Dia_setmana                36549 non-null  object
 10  Descripcio_tipus_dia       36549 non-null  object
 11  Any                        67448 non-null  float64
 12  Mes_any                    67448 non-null  int64
 13  Nom_mes                    67448 non-null  object
 14  Dia_mes                    67448 non-null  int64
 15  Hora_dia                   67448 non-null  int64
 16  Descripcio_torn            67448 non-null  object
 17  Numero_morts               59923 non-null  float64
 18  Numero_lesionats_lleus     66440 non-null  float64
 19  Numero_lesionats_greus     60153 non-null  float64
 20  Numero_victimes            66632 non-null  float64
 21  Numero_vehicles_implicats  67448 non-null  int64
 22  Coordenada_UTM_X           36549 non-null  object
 23  Coordenada_UTM_Y           36549 non-null  object
 24  Longitud                   44538 non-null  float64
 25  Latitud                    44538 non-null  float64
 26  Coordenada_UTM_X_ED50      30899 non-null  object
 27  Coordenada_UTM_Y_ED50      30899 non-null  object
 28  Longitud_WGS84             22886 non-null  float64
 29  Latitud_WGS84              22886 non-null  float64
 30  Descripcio_causa_vianant   60383 non-null  object
dtypes: float64(9), int64(6), object(16)
memory usage: 16.0+ MB

In [26]:
df_accidents[df_accidents[['Coordenada_UTM_Y_ED50', 'Coordenada_UTM_X_ED50', 'Coordenada_UTM_X', 'Coordenada_UTM_Y' ]].notna().all(axis=1)]

Empty DataFrame
Columns: [Numero_expedient, Codi_districte, Nom_districte, Codi_barri, Nom_barri, Codi_carrer, Nom_carrer, Num_postal, Descripcio_dia_setmana, Dia_setmana, Descripcio_tipus_dia, Any, Mes_any, Nom_mes, Dia_mes, Hora_dia, Descripcio_torn, Numero_morts, Numero_lesionats_lleus, Numero_lesionats_greus, Numero_victimes, Numero_vehicles_implicats, Coordenada_UTM_X, Coordenada_UTM_Y, Longitud, Latitud, Coordenada_UTM_X_ED50, Coordenada_UTM_Y_ED50, Longitud_WGS84, Latitud_WGS84, Descripcio_causa_vianant]
Index: []

[0 rows x 31 columns]

In [27]:
# Actualizamos las variables de las coordenadas combinadolas con sus variables redundantes 
df_accidents['Longitud'] = df_accidents['Longitud'].combine_first(df_accidents['Longitud_WGS84'])
df_accidents['Latitud'] = df_accidents['Latitud'].combine_first(df_accidents['Latitud_WGS84'])
df_accidents['Coordenada_UTM_X'] = df_accidents['Coordenada_UTM_X'].combine_first(df_accidents['Coordenada_UTM_X_ED50'])
df_accidents['Coordenada_UTM_Y'] = df_accidents['Coordenada_UTM_Y'].combine_first(df_accidents['Coordenada_UTM_Y_ED50'])

In [28]:
# Eliminamos las variables redundante
df_accidents.drop(columns=['Longitud_WGS84', 'Latitud_WGS84','Coordenada_UTM_X_ED50', 'Coordenada_UTM_Y_ED50'], inplace=True)

In [29]:
df_accidents.isna().sum().sort_values(ascending=False)

Dia_setmana                  30899
Descripcio_tipus_dia         30899
Num_postal                    7909
Numero_morts                  7525
Numero_lesionats_greus        7295
Descripcio_causa_vianant      7065
Numero_lesionats_lleus        1008
Numero_victimes                816
Longitud                        24
Latitud                         24
Nom_carrer                       2
Descripcio_dia_setmana           0
Codi_barri                       0
Nom_barri                        0
Codi_carrer                      0
Codi_districte                   0
Numero_expedient                 0
Nom_districte                    0
Any                              0
Hora_dia                         0
Descripcio_torn                  0
Nom_mes                          0
Dia_mes                          0
Mes_any                          0
Numero_vehicles_implicats        0
Coordenada_UTM_X                 0
Coordenada_UTM_Y                 0
dtype: int64

In [30]:
df_accidents.shape

(67448, 27)

In [31]:
df_accidents["Any"].value_counts().sort_index()

Any
2017.0    10335
2018.0     9926
2019.0    10027
2020.0     6261
2021.0     7653
2022.0     7989
2023.0     7721
2024.0     7536
Name: count, dtype: int64

In [32]:
df_accidents['Descripcio_dia_setmana'].value_counts()

Descripcio_dia_setmana
Divendres    11329
Dijous       10988
Dimecres     10805
Dimarts      10598
Dilluns      10074
Dissabte      7721
Diumenge      5933
Name: count, dtype: int64

In [33]:
# Codificamos correctamente los dias de la semana actualizando la variable Dia_setmana (mal codificada)
dias_semana = {'Dilluns': 1,
               'Dimarts': 2,
               'Dimecres': 3,
               'Dijous': 4,
               'Divendres': 5,
               'Dissabte': 6,
               'Diumenge': 7}

df_accidents['Dia_setmana'] = df_accidents['Descripcio_dia_setmana'].map(dias_semana)
df_accidents['Dia_setmana'].value_counts()

Dia_setmana
5    11329
4    10988
3    10805
2    10598
1    10074
6     7721
7     5933
Name: count, dtype: int64

In [34]:
df_accidents['Nom_barri'].value_counts()

Nom_barri
la Dreta de l'Eixample             7083
l'Antiga Esquerra de l'Eixample    3587
Sant Gervasi - Galvany             2629
la Nova Esquerra de l'Eixample     2523
la Sagrada Família                 2460
                                   ...
Can Baró                            106
Ciutat Meridiana                     88
Torre Baró                           75
Can Peguera                          48
Vallbona                             43
Name: count, Length: 75, dtype: int64

In [35]:
df_accidents['Codi_barri'].value_counts()

Codi_barri
7          6454
8          3232
26         2384
9          2275
6          2220
           ...
81-8-55      10
81-8-54       8
71-7-42       7
81-8-56       6
84-8-47       2
Name: count, Length: 148, dtype: int64

In [36]:
df_accidents.shape

(67448, 27)

In [37]:
df_accidents = limpiar_clave(df_accidents, "Numero_expedient")

# --- Dataset 1: causa conductor ---
df_causa_conductor = cargar_y_unificar(
    "../data/raw/accidents_causa_conductor",
    ["Numero_expedient", "Número_expedient"],
    ["Descripcio_causa_mediata", "Descripcio_torn"]
)

# --- Dataset 2: causa mediata ---
df_causa_mediata = cargar_y_unificar(
    "../data/raw/accidents_causa_mediata",
    ["Numero_expedient", "Número_d'expedient"],
    ["Descripcio_causa_mediata", "Descripció_causa_mediata"]
)

# --- Dataset 3: tipología ---
df_tipologia = cargar_y_unificar(
    "../data/raw/accidents_segun_tipologia",
    ["Numero_expedient", "Codi_expedient"],
    ["Descripcio_tipus_accident", "Tipus_accident"]
)

df_causa_conductor = df_causa_conductor.rename(columns={'Descripcio_causa_mediata':'Descripcio_causa_conductor'})

# --- Merge final con df_accidents ---
df_accidents = df_accidents.merge(df_causa_conductor, on="Numero_expedient", how="left")
df_accidents = df_accidents.merge(df_causa_mediata, on="Numero_expedient", how="left")
df_accidents = df_accidents.merge(df_tipologia, on="Numero_expedient", how="left")

In [38]:
# Crear un filtro booleano que indique si alguna de las palabras aparece en la columna
filtro = df_causa_conductor['Descripcio_causa_conductor'].str.contains(r'\b(matí|Tarda|Nit)\b', case=False, na=False)

# Mostrar cuántos registros cumplen la condición
f"Número de registros que contienen alguna de las palabras: {filtro.sum()}"

/tmp/ipykernel_1688/426766472.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  filtro = df_causa_conductor['Descripcio_causa_conductor'].str.contains(r'\b(matí|Tarda|Nit)\b', case=False, na=False)

'Número de registros que contienen alguna de las palabras: 0'

In [39]:
df_accidents.shape

(67448, 30)

In [40]:
df_accidents['Descripcio_tipus_accident'].value_counts()

Descripcio_tipus_accident
Col.lisió lateral                                                                  15021
Abast                                                                              13619
Col.lisió fronto-lateral                                                           11484
Atropellament                                                                       7640
Caiguda (dues rodes)                                                                5042
                                                                                   ...
Caiguda (dues rodes), Resta sortides de via, Sortida de via amb xoc o col.lisió        1
Sortida de via amb atropellament                                                       1
Abast multiple, Atropellament                                                          1
Caiguda (dues rodes), Caiguda interior vehicle, Col.lisió lateral                      1
Col.lisió frontal, Sortida de via amb xoc o col.lisió                                  1
Name: count, Length: 151, dtype: int64

In [41]:
df_accidents.isna().sum().sort_values(ascending=False)

Descripcio_tipus_dia          30899
Num_postal                     7909
Numero_morts                   7525
Numero_lesionats_greus         7295
Descripcio_causa_vianant       7065
Descripcio_causa_mediata       7039
Numero_lesionats_lleus         1008
Numero_victimes                 816
Descripcio_causa_conductor      408
Latitud                          24
Longitud                         24
Nom_carrer                        2
Descripcio_tipus_accident         2
Nom_districte                     0
Nom_mes                           0
Mes_any                           0
Any                               0
Dia_setmana                       0
Descripcio_dia_setmana            0
Codi_barri                        0
Nom_barri                         0
Codi_carrer                       0
Codi_districte                    0
Numero_expedient                  0
Hora_dia                          0
Descripcio_torn                   0
Numero_vehicles_implicats         0
Dia_mes                           0
Coordenada_UTM_X                  0
Coordenada_UTM_Y                  0
dtype: int64

In [42]:
df_accidents['Numero_morts'].value_counts()

Numero_morts
0.0    59786
1.0      137
Name: count, dtype: int64

In [43]:
df_accidents

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Numero_victimes,Numero_vehicles_implicats,Coordenada_UTM_X,Coordenada_UTM_Y,Longitud,Latitud,Descripcio_causa_vianant,Descripcio_causa_conductor,Descripcio_causa_mediata,Descripcio_tipus_accident
0,2017S000001,5,Sarrià-Sant Gervasi,26,Sant Gervasi - Galvany,187105,VIA AUGUSTA ...,0063 0063,Diumenge,7,...,1.0,1,"428887,27","4583659,1",2.151330,41.400771,No és causa del vianant,"Altres, Manca d'atenció a la conducció",Alcoholèmia,Xoc contra element estàtic
1,2017S000002,2,Eixample,5,el Fort Pienc,197302,GV CORTS CATALANES ...,0120 0120,Diumenge,7,...,1.0,2,"431987,02","4583282,61",2.182376,41.399680,No és causa del vianant,Manca d'atenció a la conducció,No hi ha causa mediata,Col.lisió fronto-lateral
2,2017S000003,7,Horta-Guinardó,33,el Baix Guinardó,265402,RDA GUINARDÓ ...,0000 0000,Diumenge,7,...,0.0,1,"430178,13","4585222,02",2.166464,41.412769,No és causa del vianant,Altres,No hi ha causa mediata,Xoc contra element estàtic
3,2017S000004,2,Eixample,6,la Sagrada Família,89004,BALMES / Rosselló ...,0531 0531,Diumenge,7,...,1.0,2,"431615,63","4583971,63",2.157359,41.393310,No és causa del vianant,"Desobeir altres senyals, Gir indegut o sense p...",No hi ha causa mediata,Col.lisió lateral
4,2017S000005,10,Sant Martí,66,el Parc i la Llacuna del Poblenou,243206,PALLARS ...,0091 0091,Diumenge,7,...,2.0,3,"432466,78","4583327,27",2.193249,41.397908,No és causa del vianant,Altres,Alcoholèmia,"Abast, Xoc contra element estàtic"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67443,2024S007547,2,Eixample,7,la Dreta de l'Eixample,169409,Corts Catalanes,603,Dimarts,2,...,1.0,1,4582460.824,430450.705,2.167002,41.388825,Altres,No determinada,<NA>,Atropellament
67444,2024S007548,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",143100,General Álvarez de Castro,2-4,Dissabte,6,...,NaN,1,4582233.737,431382.242,2.178169,41.386859,<NA>,No determinada,<NA>,Xoc contra element estàtic
67445,2024S007549,3,Sants-Montjuïc,11,el Poble Sec,198804,Paral·lel,None,Dijous,4,...,1.0,1,4580940.29,428989.313,2.149703,41.375002,<NA>,No determinada,<NA>,Caiguda interior vehicle
67446,2024S007550,3,Sants-Montjuïc,11,el Poble Sec,234001,Olímpic,1-3,Dilluns,1,...,1.0,1,4579426.054,429206.725,2.152479,41.361383,<NA>,Manca d'atenció a la conducció,Alcoholèmia,Xoc contra element estàtic
67447,2024S007551,1,Ciutat Vella,1,el Raval,701367,Raval,25X,Divendres,5,...,1.0,1,4581341.695,430668.432,2.169734,41.378764,<NA>,NaN,NaN,NaN

In [44]:
df_accidents

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Numero_victimes,Numero_vehicles_implicats,Coordenada_UTM_X,Coordenada_UTM_Y,Longitud,Latitud,Descripcio_causa_vianant,Descripcio_causa_conductor,Descripcio_causa_mediata,Descripcio_tipus_accident
0,2017S000001,5,Sarrià-Sant Gervasi,26,Sant Gervasi - Galvany,187105,VIA AUGUSTA ...,0063 0063,Diumenge,7,...,1.0,1,"428887,27","4583659,1",2.151330,41.400771,No és causa del vianant,"Altres, Manca d'atenció a la conducció",Alcoholèmia,Xoc contra element estàtic
1,2017S000002,2,Eixample,5,el Fort Pienc,197302,GV CORTS CATALANES ...,0120 0120,Diumenge,7,...,1.0,2,"431987,02","4583282,61",2.182376,41.399680,No és causa del vianant,Manca d'atenció a la conducció,No hi ha causa mediata,Col.lisió fronto-lateral
2,2017S000003,7,Horta-Guinardó,33,el Baix Guinardó,265402,RDA GUINARDÓ ...,0000 0000,Diumenge,7,...,0.0,1,"430178,13","4585222,02",2.166464,41.412769,No és causa del vianant,Altres,No hi ha causa mediata,Xoc contra element estàtic
3,2017S000004,2,Eixample,6,la Sagrada Família,89004,BALMES / Rosselló ...,0531 0531,Diumenge,7,...,1.0,2,"431615,63","4583971,63",2.157359,41.393310,No és causa del vianant,"Desobeir altres senyals, Gir indegut o sense p...",No hi ha causa mediata,Col.lisió lateral
4,2017S000005,10,Sant Martí,66,el Parc i la Llacuna del Poblenou,243206,PALLARS ...,0091 0091,Diumenge,7,...,2.0,3,"432466,78","4583327,27",2.193249,41.397908,No és causa del vianant,Altres,Alcoholèmia,"Abast, Xoc contra element estàtic"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67443,2024S007547,2,Eixample,7,la Dreta de l'Eixample,169409,Corts Catalanes,603,Dimarts,2,...,1.0,1,4582460.824,430450.705,2.167002,41.388825,Altres,No determinada,<NA>,Atropellament
67444,2024S007548,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",143100,General Álvarez de Castro,2-4,Dissabte,6,...,NaN,1,4582233.737,431382.242,2.178169,41.386859,<NA>,No determinada,<NA>,Xoc contra element estàtic
67445,2024S007549,3,Sants-Montjuïc,11,el Poble Sec,198804,Paral·lel,None,Dijous,4,...,1.0,1,4580940.29,428989.313,2.149703,41.375002,<NA>,No determinada,<NA>,Caiguda interior vehicle
67446,2024S007550,3,Sants-Montjuïc,11,el Poble Sec,234001,Olímpic,1-3,Dilluns,1,...,1.0,1,4579426.054,429206.725,2.152479,41.361383,<NA>,Manca d'atenció a la conducció,Alcoholèmia,Xoc contra element estàtic
67447,2024S007551,1,Ciutat Vella,1,el Raval,701367,Raval,25X,Divendres,5,...,1.0,1,4581341.695,430668.432,2.169734,41.378764,<NA>,NaN,NaN,NaN

In [46]:
# Guardamos el dataframe
with open('../data/processed/df_accidents.pkl', 'wb') as f:
    pickle.dump(df_accidents, f)

In [48]:
with open('../data/processed/df-meteo.pkl', 'rb') as f:
    df_meteo = pickle.load(f)

In [49]:
df_meteo

,location_id,time,temperature_2m (°C),precipitation (mm),snowfall (cm),wind_speed_10m (km/h),rain (mm),time_n
0,0,2017-01-01T00:00,7.2,0.0,0.0,7.1,0.0,2017-01-01 00:00:00
1,0,2017-01-01T01:00,7.0,0.0,0.0,8.9,0.0,2017-01-01 01:00:00
2,0,2017-01-01T02:00,4.2,0.0,0.0,11.0,0.0,2017-01-01 02:00:00
3,0,2017-01-01T03:00,4.7,0.0,0.0,10.8,0.0,2017-01-01 03:00:00
4,0,2017-01-01T04:00,4.4,0.0,0.0,10.5,0.0,2017-01-01 04:00:00
...,...,...,...,...,...,...,...,...
701275,9,2024-12-31T19:00,9.1,0.0,0.0,1.1,0.0,2024-12-31 19:00:00
701276,9,2024-12-31T20:00,9.0,0.0,0.0,3.4,0.0,2024-12-31 20:00:00
701277,9,2024-12-31T21:00,8.4,0.0,0.0,6.6,0.0,2024-12-31 21:00:00
701278,9,2024-12-31T22:00,7.8,0.0,0.0,8.1,0.0,2024-12-31 22:00:00
701279,9,2024-12-31T23:00,7.7,0.0,0.0,8.4,0.0,2024-12-31 23:00:00

In [50]:
df_accidents['Any'] = df_accidents['Any'].astype(int)
df_accidents['Any'].dtype

dtype('int64')

In [53]:
df_accidents['time_n'] = pd.to_datetime(df_accidents.apply(lambda x: f"{x['Any']}-{x['Mes_any']}-{x['Dia_mes']} {x['Hora_dia']}:00:00", axis=1))

In [54]:
df_meteo['time_n'] = pd.to_datetime(df_meteo['time'])

In [55]:
mapeo_distritos = {'Desconegut': 0,              # Montjuïc
                   'Sant Martí': 8,              # Zona marítima noreste
                   'Ciutat Vella': 0,            # Centro histórico
                   'Eixample': 1,                # Centro denso
                   'Sants-Montjuïc': 2,          # Sur de la ciudad
    'Les Corts': 3,               # Suroeste
    'Sarrià-Sant Gervasi': 4,     # Zona alta
    'Gràcia': 5,                  # Centro-norte
    'Horta-Guinardó': 6,          # Noreste
    'Nou Barris': 7,              # Norte
    'Sant Andreu': 9}             # Nordeste

In [56]:
df_accidents['location_id'] = df_accidents['Nom_districte'].map(mapeo_distritos)

In [57]:
df_merged = pd.merge(df_accidents, df_meteo, on=['time_n', 'location_id'], how='right')
df_merged

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,Dia_setmana,...,Descripcio_causa_mediata,Descripcio_tipus_accident,time_n,location_id,time,temperature_2m (°C),precipitation (mm),snowfall (cm),wind_speed_10m (km/h),rain (mm)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2017-01-01 00:00:00,0,2017-01-01T00:00,7.2,0.0,0.0,7.1,0.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2017-01-01 01:00:00,0,2017-01-01T01:00,7.0,0.0,0.0,8.9,0.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2017-01-01 02:00:00,0,2017-01-01T02:00,4.2,0.0,0.0,11.0,0.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2017-01-01 03:00:00,0,2017-01-01T03:00,4.7,0.0,0.0,10.8,0.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2017-01-01 04:00:00,0,2017-01-01T04:00,4.4,0.0,0.0,10.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2024-12-31 19:00:00,9,2024-12-31T19:00,9.1,0.0,0.0,1.1,0.0
707893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2024-12-31 20:00:00,9,2024-12-31T20:00,9.0,0.0,0.0,3.4,0.0
707894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2024-12-31 21:00:00,9,2024-12-31T21:00,8.4,0.0,0.0,6.6,0.0
707895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2024-12-31 22:00:00,9,2024-12-31T22:00,7.8,0.0,0.0,8.1,0.0
707896,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2024-12-31 23:00:00,9,2024-12-31T23:00,7.7,0.0,0.0,8.4,0.0

In [58]:
df_merged["accident"] = df_merged["Numero_expedient"].notna().astype(int)

In [62]:
df_merged['accident'].value_counts() / len(df_merged)

accident
0    0.904721
1    0.095279
Name: count, dtype: float64